export const FeedbackStatus = {
  CONNECTED: 'CONNECTED',
  DISCONNECTING: 'DISCONNECTING',
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  FAILED: 'FAILED',
};

export const StepProgress = {
  NOT_STARTED: 'NOT_STARTED',
  RUNNING: 'RUNNING',
  ENDED_OK: 'ENDED_OK',
  ENDED_ERROR: 'ENDED_ERROR',
};
